name: Deploy to Dokku

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for Dokku
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOKKU_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ivokatunaric.from.hr >> ~/.ssh/known_hosts

      - name: Deploy to Dokku
        run: |
          git remote add dokku dokku@technobabble.hr:email-post-relay
          git push dokku main:master --force
